
  [build]
  command = "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && wasm-pack build miner-client --target web --out-dir ../public/wasm && npm run build"
  publish = "public"

[[edge_functions]]
  path = "/api/link-wallet"
  function = "link-wallet"

[[edge_functions]]
  path = "/api/mine"
  function = "mine-handler"

  [[edge_functions]]
  path = "/api/ghost-config"
  function = "ghost-config"

[[edge_functions]]
  path = "/api/ghost-chat"
  function = "matrix-bridge"
  

[functions]
  directory = "netlify/functions"
  
